project_name: blog
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: blog
    ldflags:
      - -s -w
      - -X github.com/b4b4r07/blog/cmd.Version={{ .Version }}
      - -X github.com/b4b4r07/blog/cmd.BuildTag={{ .Tag }}
      - -X github.com/b4b4r07/blog/cmd.BuildSHA={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
