name: Check Empty Changelog

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Event Name: ${{ github.event_name }}"

  check-changelog:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'Release') # Check tagpr PR title
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Check for empty changelog entries
        uses: babarot/changelog-empty-check-action@v0.0.1
        id: check
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-name: 'empty-changelog' # TODO: update!

      - name: Additional steps on empty changelog
        if: steps.check.outputs.has_empty_changelog == 'true'
        run: |
          echo "Empty changelog entries found:"
          echo "${{ steps.check.outputs.empty_headers }}"
